language: java
dist: xernial
sudo: required
addons:
  postgresql: "9.4"
  apt:
    sources:
      - mysql-5.7-xenial
    packages:
      - mysql-server
      - mysql-client
services:
  - postgresql
jdk:
  - openjdk8
env:
  global:
    - _JAVA_OPTIONS="-Xmx2048m -Xms512m"
    - EMBULK_INPUT_POSTGRESQL_TEST_CONFIG=$TRAVIS_BUILD_DIR/ci/travis_postgresql.yml
    - EMBULK_INPUT_MYSQL_TEST_CONFIG=$TRAVIS_BUILD_DIR/ci/travis_mysql.yml
cache:
  directories:  # run "travis cache --delete" to delete caches
    - $HOME/.gradle
before_install:
  - sudo mysql -e "use mysql; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - mysql -u root -e "create database travis_ci_test;"
  - mysql -u root -e "grant all on travis_ci_test.* to travis@localhost identified by '';" # give 'travis' user grant to create/drop tables.
script:
  - ./gradlew --info check
